# Generated by Django 3.0.6 on 2020-08-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='titulo')),
                ('description', models.CharField(max_length=100, verbose_name='descripcion')),
                ('ingredients', models.TextField(max_length=200, verbose_name='ingrefientes')),
                ('process', models.TextField(max_length=400, verbose_name='procedimiento')),
                ('images', models.ImageField(upload_to='recipes/images')),
                ('puntuation', models.CharField(max_length=2, verbose_name='puntaje')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
