# Generated by Django 3.0.6 on 2020-08-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='images',
            field=models.ImageField(upload_to='images'),
        ),
    ]
